### ISSUE TITLE
onCompleteHandle Needs A .bind And An Additional Argument

### ISSUE THREAD

**Issue by giacomo9999** [zafar-saleem/react-todo#2]
Hi again-
In the render method of the Todo component, the line
`<button onClick={this.onCompleteHandle}>Complete</button>`
won't work as written.  Without a .bind, the method can't update {this.state} and there's no reference to which entry is supposed to be marked complete.

So onCompleteHandle needs to have a .bind and to also be supplied item.id as an argument, as below: 
`<button onClick={this.onCompleteHandle.bind(this, item.id)}>Complete</button>`

**Comment by giacomo9999** [comment]
Update: The version in this repo is actually correct...the issue is only in the Medium article.

**Comment by zafar-saleem** [comment]
Just looked into that, that part is fixed now. I am closing this issue.
